In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
data_train= pd.read_csv("C:/Users/Asus/Desktop/Data Set/insurance_train.csv")
data_test= pd.read_csv("C:/Users/Asus/Desktop/Data Set/insurance_test.csv")

In [3]:
data_train.head()

Id  Product_Info_1 Product_Info_2  Product_Info_3  Product_Info_4  \
0   2               1             D3              10        0.076923   
1   5               1             A1              26        0.076923   
2   6               1             E1              26        0.076923   
3   7               1             D4              10        0.487179   
4   8               1             D2              26        0.230769   

   Product_Info_5  Product_Info_6  Product_Info_7   Ins_Age        Ht  ...  \
0               2               1               1  0.641791  0.581818  ...   
1               2               3               1  0.059701  0.600000  ...   
2               2               3               1  0.029851  0.745455  ...   
3               2               3               1  0.164179  0.672727  ...   
4               2               3               1  0.417910  0.654545  ...   

   Medical_Keyword_40  Medical_Keyword_41  Medical_Keyword_42  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   Medical_Keyword_43  Medical_Keyword_44  Medical_Keyword_45  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   Medical_Keyword_46  Medical_Keyword_47  Medical_Keyword_48  Response  
0                   0                   0                   0         8  
1                   0                   0                   0         4  
2                   0                   0                   0         8  
3                   0                   0                   0         8  
4                   0                   0                   0         8  

[5 rows x 128 columns]

In [4]:
data_test.head()

Id  Product_Info_1 Product_Info_2  Product_Info_3  Product_Info_4  \
0   1               1             D3              26        0.487179   
1   3               1             A2              26        0.076923   
2   4               1             D3              26        0.144667   
3   9               1             A1              26        0.151709   
4  12               1             A1              26        0.076923   

   Product_Info_5  Product_Info_6  Product_Info_7   Ins_Age        Ht  ...  \
0               2               3               1  0.611940  0.781818  ...   
1               2               3               1  0.626866  0.727273  ...   
2               2               3               1  0.582090  0.709091  ...   
3               2               1               1  0.522388  0.654545  ...   
4               2               3               1  0.298507  0.672727  ...   

   Medical_Keyword_39  Medical_Keyword_40  Medical_Keyword_41  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   Medical_Keyword_42  Medical_Keyword_43  Medical_Keyword_44  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   Medical_Keyword_45  Medical_Keyword_46  Medical_Keyword_47  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   1   
4                   0                   0                   0   

   Medical_Keyword_48  
0                   0  
1                   0  
2                   0  
3                   1  
4                   0  

[5 rows x 127 columns]

In [5]:
data_train.shape, data_test.shape

((59381, 128), (19765, 127))

In [6]:
data_train.isnull().sum()

Id                         0
Product_Info_1             0
Product_Info_2             0
Product_Info_3             0
Product_Info_4             0
Product_Info_5             0
Product_Info_6             0
Product_Info_7             0
Ins_Age                    0
Ht                         0
Wt                         0
BMI                        0
Employment_Info_1         19
Employment_Info_2          0
Employment_Info_3          0
Employment_Info_4       6779
Employment_Info_5          0
Employment_Info_6      10854
InsuredInfo_1              0
InsuredInfo_2              0
InsuredInfo_3              0
InsuredInfo_4              0
InsuredInfo_5              0
InsuredInfo_6              0
InsuredInfo_7              0
Insurance_History_1        0
Insurance_History_2        0
Insurance_History_3        0
Insurance_History_4        0
Insurance_History_5    25396
                       ...  
Medical_Keyword_20         0
Medical_Keyword_21         0
Medical_Keyword_22         0
Medical_Keywor

In [7]:
data_train = data_train.fillna(data_train.median())

In [8]:
data_test.isnull().sum()

Id                        0
Product_Info_1            0
Product_Info_2            0
Product_Info_3            0
Product_Info_4            0
Product_Info_5            0
Product_Info_6            0
Product_Info_7            0
Ins_Age                   0
Ht                        0
Wt                        0
BMI                       0
Employment_Info_1         3
Employment_Info_2         0
Employment_Info_3         0
Employment_Info_4      2137
Employment_Info_5         0
Employment_Info_6      3787
InsuredInfo_1             0
InsuredInfo_2             0
InsuredInfo_3             0
InsuredInfo_4             0
InsuredInfo_5             0
InsuredInfo_6             0
InsuredInfo_7             0
Insurance_History_1       0
Insurance_History_2       0
Insurance_History_3       0
Insurance_History_4       0
Insurance_History_5    8105
                       ... 
Medical_Keyword_19        0
Medical_Keyword_20        0
Medical_Keyword_21        0
Medical_Keyword_22        0
Medical_Keyword_23  

In [9]:
data_test = data_test.fillna(data_test.median())

In [10]:
pli_train = data_train.drop(['Response','Id','Product_Info_2'],axis=1)


In [17]:
y_pli_train =data_train['Response']

In [13]:
pli_test = data_test.drop(['Id','Product_Info_2'],axis=1)

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [18]:
x_train,x_test,y_train,y_test = train_test_split(pli_train,y_pli_train)
lr =LogisticRegression()


In [19]:
score =cross_val_score(lr,x_train,y_train,cv=10, scoring = 'accuracy')

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver 

In [24]:
print(score)


[0.50572134 0.49887792 0.50022442 0.50269421 0.49607007 0.50797215
 0.50808625 0.5        0.51022242 0.49809032]


In [25]:
print(score.mean())

0.5027959089416719


In [27]:
lr.fit(x_train,y_train)


C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
lr.score(x_train,y_train)

0.508521387672617

In [29]:
predicted = lr.predict(pli_test)

In [30]:
print(predicted)

[1 6 6 ... 7 5 6]


In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
knn =KNeighborsClassifier(n_neighbors=5)
score = cross_val_score(knn,x_train,y_train,cv=5,scoring='accuracy')

In [33]:
print(score)

[0.32615039 0.32768298 0.3265604  0.33632791 0.32771788]


In [34]:
print(score.mean())

0.3288879109665424


In [37]:
knn1 =KNeighborsClassifier(n_neighbors=10)
score = cross_val_score(knn,x_train,y_train,cv=5,scoring='accuracy')

In [38]:
print(score.mean())

0.3577629908961314


In [39]:
knn1 =KNeighborsClassifier(n_neighbors=20)
score = cross_val_score(knn,x_train,y_train,cv=5,scoring='accuracy')

In [40]:
print(score.mean())

0.3577629908961314


In [41]:
knn1.fit(x_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=20, p=2,
                     weights='uniform')

In [53]:
knn1.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=20, p=2,
                     weights='uniform')

In [54]:
knn1.score(x_train,y_train)

0.4315482205007298

In [42]:
predicted= knn1.predict(pli_test) 

In [43]:
print(predicted)

[2 8 6 ... 1 6 4]


In [45]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier(n_estimators=10,criterion='gini')

In [46]:
score = cross_val_score(rf,x_train,y_train,cv=10,scoring='accuracy')

In [47]:
print(score.mean())

0.5143367554890065


In [48]:
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [55]:
rf.score(x_train,y_train)

0.99003031323678

In [56]:
predicted =  rf.predict(pli_test)

In [57]:
print(predicted)

[6 2 6 ... 6 2 1]


In [52]:
rf1 = RandomForestClassifier(n_estimators=20, criterion='gini')
score = cross_val_score(rf1,x_train,y_train,cv=10,scoring='accuracy')
print(score.mean())

0.5442677696038241


In [58]:
rf1.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [59]:
rf1.score(x_train,y_train)

0.9982710227910632

In [60]:
predicted = rf.predict(pli_test)
print(predicted)

[6 2 6 ... 6 2 1]


In [62]:
response =predicted
result1 = pd.DataFrame()

In [63]:
ID = data_test['Id']

In [65]:
result1['Id']=ID
result1['response']=response

In [66]:
result1.head()

Id  response
0   1         6
1   3         2
2   4         6
3   9         7
4  12         8

In [67]:
result1.to_csv('result1.csv',index=False)